# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4
# vmImage: 'windows-latest'

trigger:
- main

# top level is the Stage - contains jobs
stages:
- stage: Build
  pool:
    name: Default
 
# define some variables for use later on
  variables:
    solution: '**/*.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'
    jimVar1: 'hello'

  jobs:
# jobs contain steps
  - job: Build
    displayName: Build
    steps:
# steps can be tasks, scripts, etc
    - script: echo Build step 1

    - checkout: self
      clean: true

    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk'
      inputs:
        packageType: 'sdk'
        version: '6.0.x'
        includePreviewVersions: true

    - task: NuGetAuthenticate@0
      displayName: NuGet Authenticate
      inputs:
        nuGetServiceConnections: $(nuget-service-connection)
        forceReinstallCredentialProvider: true

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        projects: 'src/**/*.csproj'
        arguments: ' /p:custom_build_environment=azure'
        noCache: true

  - job: A2
    steps:
    - script: echo step A2
- stage: B
  pool:
    name: Default
  jobs:
  - job: B1
    steps:
    - script: echo step   B1

